version: "3.9"

services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    command: "yarn start"
    volumes:
      - ./:/api

  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5431:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d defaultdb"]
      interval: 10s
      timeout: 5s
      retries: 5
